### PR TITLE
Fix php stan level 5

### PR DESCRIPTION
**Pull request by okom3pom**

### CODE REVIEW

**Comment by nenes25** [comment]
We should wait the merge of #129 before ( so we can remove the ignore of the errors in phpstan configuration file )

**Comment by okom3pom** [comment]
Yes when the 129 is merge i modify the  phpstan configuration file

**Comment by okom3pom** [comment]
Done @nenes25

**Review by nenes25 — APPROVED** [review]
Phpstan checks are good , so it looks good to me :smile:

**Review by jf-viguier — APPROVED** [review]

**Pull request merged**
