### PR TITLE
Improve RenameModule command

### PR DESCRIPTION
**Pull request by Kaudaj**
### What's new

- Separate 'find and replace' logic in a dedicated tool
- Improve cased replace pairs parsing with better words functions and words sanitizing
- Add PHPUnit tests for case formatting and files parsing
- Make new module installation optional to prevent problems in production environment
- Install node modules for the new module
- Add more PHPDoc 
- Cleaner output with less warnings and more spaces

### CODE REVIEW

**Comment by Kaudaj** [comment]
### /!\ Need your help /!\
@SebSept @okom3pom @jf-viguier @nenes25

image

Could you test the command and tell if you get this annoying bunch of warnings about not found translations when new module installation begins? Do you know how to suppress them?

**Comment by Kaudaj** [comment]
Resolved thanks to @okom3pom : warnings disappear when using pr:mo install command!

**Review by jf-viguier — COMMENTED** [review]
For me, module install or unistall is not in the scope of this command.

**Comment by Kaudaj** [comment]
> For me, module install or unistall is not in the scope of this command.

Installation of new module is now optional!

**Comment by SebSept** [comment]
@Kaudaj : can you resolve the conflicts ?
As soon as it's done, I'll merge.

**Comment by Kaudaj** [comment]
@SebSept Ok nice, I try to do it this weekend!

**Comment by Kaudaj** [comment]
@SebSept Done, ready to merge! 😃

**Comment by SebSept** [comment]
Great, I'll merge tonight.

**Pull request merged**
