### PR TITLE
Update php dev tools

### PR DESCRIPTION
**Pull request by SebSept**
I also updated the php minimal version constraint, it was only set at php 7.1

### CODE REVIEW

**Comment by SebSept** [comment]
I've ran the fixer on my machine, the results are no the same as in the workflow ... ⁉️ 
any idea of what is happening ?

**Comment by SebSept** [comment]
not, sure, but maybe, the composer cache key ..

**Comment by SebSept** [comment]
ready for review.

**Review by Kaudaj — APPROVED** [review]
Ah yea, was wondering too why php minimal version was still set at 7.1... Great, it will be less confusing!

**Pull request merged**
