### PR TITLE
Command clear cache files

### PR DESCRIPTION
**Pull request by SebSept**
Tested with success on linux with prestashop 1.7.5.0.

I guess it will not run on Windows :tm: ..

### CODE REVIEW

**Comment by nenes25** [comment]
Do you start your branch from master branch ?
Some changes are not related with the new command

**Comment by SebSept** [comment]
I guess I've made a nasty rebase.

Should I make another clean pull request ?

**Comment by nenes25** [comment]
No way to clean this one ?

**Comment by SebSept** [comment]
new clean PR -> #42

**Pull request closed without merging**
