### PR TITLE
Version command

### PR DESCRIPTION
**Pull request by SebSept**
display the fop console version.
To check that the version is up to date.
[asciicast](https://asciinema.org/a/eUkqHXt7AGiylc6Xfm9IvynyW)

### CODE REVIEW

**Comment by SebSept** [comment]
> Seems great to me!
> 
> Just to be sure, registered version = database version and disk version = files version ?

That's it, maybe it's not so clear, I'll try some improvement.
> Adding last released version and colors (red when version is not the last for local ones, green for the opposite) would be a plus but as it is, I approve!

good idea. I'll do it.

**Comment by SebSept** [comment]
> It's work well, for the last u can use https://api.github.com/repos/friends-of-presta/fop_console/releases

Thanks for the tip. I'll implement this too.

**Comment by SebSept** [comment]
A last thing before merging, the command name.

It must follow 'fop:domain: action' .
Any idea ?

**Comment by Kaudaj** [comment]
`fop:about:version` should be great imo!

**Pull request merged**
