### PR TITLE
Clear cache : windows port

### PR DESCRIPTION
**Pull request by jf-viguier**
deleteOldCacheDirectory doesn't work. I need help. /S command line argument is always escaped.

### CODE REVIEW

**Comment by SebSept** [comment]
Any chance, you'll continue to investigate @jf-viguier ?
Maybe we can close this PR for a cleaner repo ?

**Comment by jf-viguier** [comment]
@SebSept don't close it, I'll do it

**Comment by jf-viguier** [comment]
@SebSept @nenes25 I've done it, please review

**Review by SebSept — APPROVED** [review]
Look good.
Tested positively on linux / php 5.4 / prestashop 1.7.6.4

**Pull request merged**
