### PR TITLE
phpstan level 5 ...

### PR DESCRIPTION
**Pull request by SebSept**

### CODE REVIEW

**Review by okom3pom — APPROVED** [review]
Ok

**Comment by okom3pom** [comment]
We can close this issue  https://github.com/friends-of-presta/fop_console/issues/136 ?

**Comment by SebSept** [comment]
not yet.
There is one error, that may be solved.

**Comment by SebSept** [comment]
I don't know how to solve the reported error 'Call to an undefined method Symfony\Component\Console\Application::getKernel()'
So this is ready to merge.

**Review by okom3pom — APPROVED** [review]

**Review by nenes25 — APPROVED** [review]

**Pull request merged**
