### PR TITLE
62 validate hook name

### PR DESCRIPTION
**Pull request by nenes25**
Improve issue #62 by falling creating a new hook if it's name is invalid or start with hook
image

### CODE REVIEW

**Review by okom3pom — APPROVED** [review]

**Review by SebSept — APPROVED** [review]
cool :)

**Review by SebSept — COMMENTED** [review]
The new validation is fine (Core Validate + start with 'hook').
But it happens only on interactive mode, not if hookname is provided as command's argument.

**Comment by nenes25** [comment]
Thanks for the feedback.
So some changes are still needed.
I'll check and ask for a new validation after :smile:

**Comment by SebSept** [comment]
I pushed some commits right now, but I can't see them ...

**Comment by SebSept** [comment]
I've made a PR for my requested changes @nenes25 , can you review / merge them ?
https://github.com/nenes25/fop_console/pull/2

**Review by SebSept — CHANGES_REQUESTED** [review]
https://github.com/nenes25/fop_console/pull/2

**Comment by nenes25** [comment]
Thanks your code is good :)
I've merged the code and push to the branch.
So i'll merge it also :)

**Pull request merged**
