### PR TITLE
Rearrange src/commands directory following the new conventions

### PR DESCRIPTION
**Pull request by Kaudaj**
Rearrange src/commands directory following the new conventions defined in issue #85.

### CODE REVIEW

**Comment by Kaudaj** [comment]
Question: Should we add a convention that requires a verb for the action?

The drawback I see is that the command names will be longer. Unless we apply this convention for class names only, but we would have a problem of consistency.

**Comment by SebSept** [comment]
Converted to draft.
MUST NOT be merged now because it introduce breaking changes.
And we should also have a phpstan to ensure commands respect the schema.
@Kaudaj is currently working on a validator that could be used inside the phpstan rule I created. #96 

There is (at least) 2 different ways to switch the command names : 
- raw : just change and let users change there scripts and habits
- shadow current commands with a 'redirect' to the current name + a deprecation warning ( à la Symfony ) if possible. Then remove the shadows in the next major release.

**Comment by SebSept** [comment]
The Validator in a class for the main Symfony code, not for testing Symfony, so it's normal to find it in src.

Here [https://github.com/symfony/symfony/tree/5.4/src/Symfony/Component/Dotenv]() we can see a folder Tests, it looks like the tests folder are at the same of the components, in a src folder. (it will be src/Tests/Validator for us, because it's a generic test)
For prestashop, tests are at the root.

Having a test folder at the level looks good but is not the PrestaShop way.

So it's possible to : 
- create a `tests` folder : require additionnal autoload config. | easy to remove the tests for the release
- create tests folder at the component level : no additonnal autoload | more complicated/risky to remove for release.

...

**Comment by SebSept** [comment]
Yep, looks good to me.
WDYT @nenes25 ?

**Review by SebSept — APPROVED** [review]
Great job !
I can see backward compatibility is ok.
You've made some tests 🎉 👍🏼 
I've just tested a few commands, look good to me :)

**Review by nenes25 — APPROVED** [review]
Good Job !
It's fine to me too  :fireworks: 
I've discovered when testing that if you use the command `bin/console list fop` alias are listed too. :smile:

**Pull request merged**
