### PR TITLE
Details on php cs fixer failure - fixes #198

### LINKED ISSUE #198: Display more details for PHP-CS-Fixer errors
PHP-CS-Fixer doesn't give enough feedback when there are errors.
It should indicate which lines are problematic in each file.

image

### PR DESCRIPTION
**Pull request by SebSept**

### CODE REVIEW

**Comment by SebSept** [comment]
You can see the error on line 15, there a space that needs to be removed.
https://github.com/friends-of-presta/fop_console/runs/4056594115?check_suite_focus=true
Capture d’écran de 2021-10-30 21-41-55

**Comment by SebSept** [comment]
I've forced push to remove the demo commit.

**Review by Kaudaj — APPROVED** [review]
Thanks!

**Review by nenes25 — APPROVED** [review]
Nice ! :smile:

**Pull request merged**
